services:
  auth_service:
    build: 
      context: .
      dockerfile: ./apps/authorization/Dockerfile
    command: npm run start:authorization:debug
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - .env
      - ./apps/authorization/.env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - postgres_db
  
  url_service:
    build: 
      context: .
      dockerfile: ./apps/url_shortener/Dockerfile

    command: npm run start:url_shortener:debug
    ports:
      - 4000:3000
      - 9228:9229
    env_file:
      - .env
      - ./apps/url_shortener/.env
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    depends_on:
      - auth_service
      - postgres_db

  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
      - ./apps/url_shortener/.env
    volumes:
     - "../data/:/var/lib/postgresql/data"
