services:
  auth_service:
    build: .
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - ./apps/.env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - postgres_db
  
  url_service:
    build: 
      context: ./url_shortner
      dockerfile: Dockerfile

    command: npm run start:debug
    ports:
      - 4000:3000
      - 9228:9229
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - auth_service
      - postgres_db

  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
     - "../data/:/var/lib/postgresql/data"