services:
  url_service:
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
     - "../data/:/var/lib/postgresql/data"